### ISSUE TITLE
How can I add my README?

### ISSUE THREAD

**Issue by AvidCoder101** [ming-tsai/ming-tsai#23]
@ming-tsai just wanted to ask how I could add my profile to your README? Thanks

**Comment by ming-tsai** [comment]
> @ming-tsai just wanted to ask how I could add my profile to your README? Thanks

Please access this [file](https://github.com/ming-tsai/ming-tsai/blob/master/src/data/users.ts) and add your github user name on the array

**Comment by AvidCoder101** [comment]
Thank you I will follow the instructions.
